### ISSUE TITLE
[CHORE] Update copyright year

### ISSUE THREAD

**Issue by sunsheeppoplar** [msb2170/msb2170.github.io#2]
**Issue:** Currently it reads 2022. Presumably it was hardcoded. A suggestion would to be to template some method off the `Date` class so you don't ever have to think about it again. Probably can test this by manually messing with your system clock and seeing if the year reflects correctly

**Comment by msb2170** [comment]
I ended up using a JS method to get the current year and then grabbing that and reading that into the html instead of hardcoding it. Of course that messed up the CSS so I had to adjust that. Anyway, it works now even if you change the system clock to some weird future year.

**Comment by sunsheeppoplar** [comment]
@msb2170 In the future you can also use `resolves #2` in your commit message so you don't have to close these manually

**Comment by sunsheeppoplar** [comment]
> I ended up using a JS method to get the current year and then grabbing that and reading that into the html instead of hardcoding it. Of course that messed up the CSS so I had to adjust that. Anyway, it works now even if you change the system clock to some weird future year.

yeah, classic 😆
